//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from HTMLParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="HTMLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IHTMLParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.htmlDocument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlDocument([NotNull] HTMLParser.HtmlDocumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.htmlDocument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlDocument([NotNull] HTMLParser.HtmlDocumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.htmlElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlElements([NotNull] HTMLParser.HtmlElementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.htmlElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlElements([NotNull] HTMLParser.HtmlElementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.htmlElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlElement([NotNull] HTMLParser.HtmlElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.htmlElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlElement([NotNull] HTMLParser.HtmlElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.htmlContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlContent([NotNull] HTMLParser.HtmlContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.htmlContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlContent([NotNull] HTMLParser.HtmlContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.htmlAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlAttribute([NotNull] HTMLParser.HtmlAttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.htmlAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlAttribute([NotNull] HTMLParser.HtmlAttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.htmlAttributeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlAttributeName([NotNull] HTMLParser.HtmlAttributeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.htmlAttributeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlAttributeName([NotNull] HTMLParser.HtmlAttributeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.htmlAttributeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlAttributeValue([NotNull] HTMLParser.HtmlAttributeValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.htmlAttributeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlAttributeValue([NotNull] HTMLParser.HtmlAttributeValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.htmlTagName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlTagName([NotNull] HTMLParser.HtmlTagNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.htmlTagName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlTagName([NotNull] HTMLParser.HtmlTagNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.htmlChardata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlChardata([NotNull] HTMLParser.HtmlChardataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.htmlChardata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlChardata([NotNull] HTMLParser.HtmlChardataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.htmlMisc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlMisc([NotNull] HTMLParser.HtmlMiscContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.htmlMisc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlMisc([NotNull] HTMLParser.HtmlMiscContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.htmlComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlComment([NotNull] HTMLParser.HtmlCommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.htmlComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlComment([NotNull] HTMLParser.HtmlCommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.xhtmlCDATA"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXhtmlCDATA([NotNull] HTMLParser.XhtmlCDATAContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.xhtmlCDATA"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXhtmlCDATA([NotNull] HTMLParser.XhtmlCDATAContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.dtd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDtd([NotNull] HTMLParser.DtdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.dtd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDtd([NotNull] HTMLParser.DtdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.xml"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXml([NotNull] HTMLParser.XmlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.xml"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXml([NotNull] HTMLParser.XmlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.scriptlet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScriptlet([NotNull] HTMLParser.ScriptletContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.scriptlet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScriptlet([NotNull] HTMLParser.ScriptletContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScript([NotNull] HTMLParser.ScriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScript([NotNull] HTMLParser.ScriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HTMLParser.style"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStyle([NotNull] HTMLParser.StyleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HTMLParser.style"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStyle([NotNull] HTMLParser.StyleContext context);
}
